version: 0.2

phases:
  pre_build:
    commands:
      - echo "Logging in to Amazon ECR..."
      - aws ecr get-login-password --region us-west-2 | docker login --username AWS --password-stdin 248189933829.dkr.ecr.us-west-2.amazonaws.com
      - REPO_NAME="my-web-app"
      - IMAGE_TAG=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c1-7)
      - echo "Using Image Tag: $IMAGE_TAG"

  build:
    commands:
      - echo "Building the Docker image..."
      - docker build -t $REPO_NAME:$IMAGE_TAG .
      - docker tag $REPO_NAME:$IMAGE_TAG 248189933829.dkr.ecr.us-west-2.amazonaws.com/$REPO_NAME:$IMAGE_TAG

  post_build:
    commands:
      - echo "Pushing the image to Amazon ECR..."
      - docker push 248189933829.dkr.ecr.us-west-2.amazonaws.com/$REPO_NAME:$IMAGE_TAG
      - echo "Creating imagedefinitions.json for CodeDeploy..."
      - printf '[{"name":"my-web-app-container","imageUri":"248189933829.dkr.ecr.us-west-2.amazonaws.com/%s:%s"}]' $REPO_NAME $IMAGE_TAG > imagedefinitions.json
      - cat imagedefinitions.json  

artifacts:
  files:
    - imagedefinitions.json

